org.gradle.jvmargs=-Xmx2G
org.gradle.parallel=true
org.gradle.caching=true

plugin_group=Varyon
plugin_name=Varyon-RPG
plugin_description=Système RPG principal (métiers, classes, interface)
plugin_author=Varyon
plugin_website=
plugin_main_entrypoint=fr.varyon.vrpg.VaryonRpgPlugin
server_version=2026.03.26-89796e57b
